USE `kartaldb`;


DROP PROCEDURE IF EXISTS `ausgabenADD`;
DROP PROCEDURE IF EXISTS `ausgabenDetailsDS`;
DROP PROCEDURE IF EXISTS `borcAdd`;
DROP PROCEDURE IF EXISTS `borcEdit`;
DROP PROCEDURE IF EXISTS `copyEinAusgabe`;
DROP PROCEDURE IF EXISTS `deleteEinAusgabe`;
DROP PROCEDURE IF EXISTS `einAusgabeAdd`;
DROP PROCEDURE IF EXISTS `einAusgabeEdit`;
DROP PROCEDURE IF EXISTS `einJahresPrognose`;
DROP PROCEDURE IF EXISTS `einJahresPrognose2`;
DROP PROCEDURE IF EXISTS `EinnahmenAusgabenPie`;
DROP PROCEDURE IF EXISTS `externKorrektur`;
DROP PROCEDURE IF EXISTS `findID`;
DROP PROCEDURE IF EXISTS `grafik_Einnahmen_Ausgaben`;
DROP PROCEDURE IF EXISTS `monateAusgabenDS`;
DROP PROCEDURE IF EXISTS `monateDS`;
DROP PROCEDURE IF EXISTS `PDF_Almanya_Upload`;
DROP PROCEDURE IF EXISTS `PDF_Ausgaben_Upload`;
DROP PROCEDURE IF EXISTS `PDF_Upload`;
DROP PROCEDURE IF EXISTS `removeAusgaben`;
DROP PROCEDURE IF EXISTS `removeBorclar`;
DROP PROCEDURE IF EXISTS `removeTaksitler`;
DROP PROCEDURE IF EXISTS `removeTaksitlerAlmanya`;
DROP PROCEDURE IF EXISTS `spSummenRechner`;
DROP PROCEDURE IF EXISTS `taksitADD`;
DROP PROCEDURE IF EXISTS `taksitAlmanyaADD`;
DROP PROCEDURE IF EXISTS `taksitAlmanyaEdit`;
DROP PROCEDURE IF EXISTS `taksitEdit`;
DROP PROCEDURE IF EXISTS `taksitlerAlmanyaDS`;
DROP PROCEDURE IF EXISTS `taksitlerAlmanyaDS_all`;
DROP PROCEDURE IF EXISTS `taksitlerAlmanyaPie`;
DROP PROCEDURE IF EXISTS `taksitlerDS`;
DROP PROCEDURE IF EXISTS `taksitlerDS_all`;
DROP PROCEDURE IF EXISTS `taksitlerDS_all_cart`;
DROP PROCEDURE IF EXISTS `taksitlerDS_cart`;
DROP PROCEDURE IF EXISTS `taksitler_down`;
DROP PROCEDURE IF EXISTS `taksitler_up`;
DROP PROCEDURE IF EXISTS `uebersichtDS`;
DROP PROCEDURE IF EXISTS `uebersichtDS2;



DROP TABLE IF EXISTS  `einausgaben`; 
DROP TABLE IF EXISTS  `karten`;
DROP TABLE IF EXISTS  `monats_ausgaben`;
DROP TABLE IF EXISTS  `prognosedaten`;
DROP TABLE IF EXISTS  `taksitler`;
DROP TABLE IF EXISTS  `taksitler_almanya`;
DROP TABLE IF EXISTS  `uebersicht`;
DROP TABLE IF EXISTS  `wechselkurse`;


